<a href="https://colab.research.google.com/github/nithin1762/2024-stat-ml-assignments/blob/main/Assignment-8_SML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Question 1


**Below is an example dataset with 10 students (rows), 5 features, and a binary target label (Pass/Fail). The target label is 1 if the student is predicted to pass, and 0 if they are predicted to fail.**

*Import necessary datasets*

In [12]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

*Create an array for features and target-variables*

In [13]:
data1 = {
    'X1': [10, 5, 15, 2, 12, 8, 14, 3, 11, 6],
    'X2': [90, 60, 95, 30, 85, 75, 92, 50, 88, 65],
    'X3': [85, 70, 90, 50, 88, 65, 93, 55, 80, 60],
    'X4': [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    'X5': [100, 80, 100, 40, 90, 70, 95, 60, 85, 75],
    'Pass/Fail': [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
}

df = pd.DataFrame(data1)
df.head()

X1  X2  X3  X4   X5  Pass/Fail
0  10  90  85   1  100          1
1   5  60  70   0   80          0
2  15  95  90   1  100          1
3   2  30  50   0   40          0
4  12  85  88   1   90          1

*Dropping the pass/fail class and declaring it as a target-variable*

In [14]:
X = df.drop('Pass/Fail', axis=1)
Y = data1['Pass/Fail'] #target-variable
Y

[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

*Splitting the data into training and testing sets*

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

*Initializing the Logistic Regression Model*

In [16]:
lo_R = LogisticRegression()

*Training the logistic regression model*

In [17]:
lo_R.fit(X_train, Y_train)

LogisticRegression()

*Predicting the test Values:*

In [18]:
predictions = lo_R.predict(X_test)
predictions

array([1, 1])

*Printing the out-put*

In [19]:
passed = 0
fail = 0

for i in range(len(predictions)):
  if predictions[i] == 1:
    passed += 1
  else:
    fail += 1

print("Number of students who passed:", passed)
print("Number of students who failed:", fail)

print("Predicted Pass/Fail (1 for Pass, 0 for Fail):")
print(predictions)

Number of students who passed: 2
Number of students who failed: 0
Predicted Pass/Fail (1 for Pass, 0 for Fail):
[1 1]


*Dataframe for passed and failed students*

In [20]:
df_end = pd.DataFrame({'Passed': passed, 'Failed': fail}, index=[0])
df_end

Passed  Failed
0       2       0

#Question 2

**Implement a logistic regression model to train above data, and find the accuracy.**

*Import the necessary datasets*

In [21]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.linear_model import LogisticRegression

*Upload the given data-set*

In [22]:
data2 = pd.read_csv('/content/diabetes_data_upload.csv')
data2.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

*Calling out the Variables and declaring the target-variable.*

In [23]:
x0 = 1
x1 = data2['Age']
x2 = data2['Gender']
x3 = data2['Polyuria']
x4 = data2['Polydipsia']
x5 = data2['sudden weight loss']
x6 = data2['weakness']
x7 = data2['Polyphagia']
x8 = data2['Genital thrush']
x9 = data2['visual blurring']
x10 = data2['Itching']
x11 = data2['Irritability']
x12 = data2['delayed healing']
x13 = data2['partial paresis']
x14 = data2['muscle stiffness']
x15 = data2['Alopecia']
x16 = data2['Obesity']

#TARGET VARIABLE.
y = data2['class']

*Mapping the variables and target-variable.*

In [24]:
'''.map({'given_data1': converted_data1, 'given_data2': converted_data2})'''
x2 = x2.map({'Male': 1, 'Female': 0})
x3 = x3.map({'Yes': 1, 'No': 0})
x4 = x4.map({'Yes': 1, 'No': 0})
x5 = x5.map({'Yes': 1, 'No': 0})
x6 = x6.map({'Yes': 1, 'No': 0})
x7 = x7.map({'Yes': 1, 'No': 0})
x8 = x8.map({'Yes': 1, 'No': 0})
x9 = x9.map({'Yes': 1, 'No': 0})
x10 = x10.map({'Yes': 1, 'No': 0})
x11 = x11.map({'Yes': 1, 'No': 0})
x12 = x12.map({'Yes': 1, 'No': 0})
x13 = x13.map({'Yes': 1, 'No': 0})
x14 = x14.map({'Yes': 1, 'No': 0})
x15 = x15.map({'Yes': 1, 'No': 0})
x16 = x16.map({'Yes': 1, 'No': 0})

y = y.map({'Positive': 1, 'Negative': 0})

*Putting these values into an array*

In [25]:
X = np.array(list(zip(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16)))
Y = np.array(y)

*Training and Testing the data*

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

*X_train*

In [27]:
X_train

array([[27,  1,  0, ...,  0,  0,  0],
       [47,  1,  0, ...,  0,  0,  1],
       [66,  0,  1, ...,  1,  0,  0],
       ...,
       [70,  1,  0, ...,  0,  1,  0],
       [48,  1,  1, ...,  0,  0,  0],
       [64,  1,  0, ...,  0,  0,  0]])

*X_test*

In [28]:
X_test

array([[67,  1,  0, ...,  1,  1,  1],
       [47,  1,  1, ...,  1,  0,  0],
       [43,  0,  1, ...,  1,  0,  1],
       ...,
       [46,  0,  1, ...,  1,  0,  0],
       [48,  0,  1, ...,  1,  1,  1],
       [33,  1,  0, ...,  0,  0,  0]])

*Y_train*

In [29]:
Y_train

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,

Y_test

In [30]:
Y_test

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1])

*Initializing the Logistic-Regression Model*

In [31]:
lo_r = LogisticRegression()

*Fitting the training value for X and Y*

In [35]:
lo_r.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

*Predict using the trained model on the test data*

In [33]:
yp = lo_r.predict(X_test)

*Calculate accuracy on the test dataset*

In [34]:
corr_pred = 0
for i in range(len(Y_test)):
  if Y_test[i] == yp[i]:
    corr_pred += 1

accuracy = corr_pred / len(Y_test)*100
print(accuracy)

95.1923076923077
